### ISSUE TITLE
Release GML 3.2.1 r12 in Beta

### ISSUE THREAD

**Issue by bermud** [opengeospatial/teamengine#12]
### Summary
- Added tests for gml:Curve geometries containing the following types of curve segment: GeodesicString/Geodesic, ArcString/Arc/Circle, ArcByCenterPoint/CircleByCenterPoint.
- Added tests for gml:CompositeCurve, vml:OrientableCurve.
- Updated dependency: geomatics-geotk-1.4. 
### Tasks
- [ ] Replace ets-gml-3.2.1-r12.jar
- [ ] Replace geomatics-geotk-1.4.jar
- [ ] Remove old jars
- [ ] Update config file with revision 3.2.1-r12
- [ ] Update gml/3.2.1 under scripts folder
